"""Initial migration.

Revision ID: e9a3b3b3d3b3
Revises: 
Create Date: 2025-11-14 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a3b3b3d3b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('item_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('endereco', sa.String(length=100), nullable=True),
    sa.Column('codigo_opcional', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('un', sa.String(length=10), nullable=True),
    sa.Column('dimensao', sa.String(length=50), nullable=True),
    sa.Column('cliente', sa.String(length=100), nullable=True),
    sa.Column('qtd_estoque', sa.Float(), nullable=False),
    sa.Column('estoque_minimo', sa.Float(), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('estoque_detalhe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_estoque_id', sa.Integer(), nullable=False),
    sa.Column('lote', sa.String(length=100), nullable=False),
    sa.Column('item_nf', sa.String(length=100), nullable=True),
    sa.Column('nf', sa.String(length=100), nullable=True),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('estacao', sa.String(length=50), nullable=True),
    sa.Column('status_validade', sa.String(length=50), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('data_entrada', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_estoque_id'], ['item_estoque.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('data_movimentacao', sa.DateTime(), nullable=True),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('usuario', sa.String(length=100), nullable=True),
    sa.Column('etapa', sa.String(length=100), nullable=True),
    sa.Column('lote', sa.String(length=100), nullable=True),
    sa.Column('item_nf', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item_estoque.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacao')
    op.drop_table('estoque_detalhe')
    op.drop_table('item_estoque')
    op.drop_table('user')
    # ### end Alembic commands ###
